### ISSUE TITLE
feat/member

### ISSUE THREAD

**Issue by JonggwanMoon** [cheoljundev/o2-market#23]
## Description

설명을 작성해주세요!

## Todos

- [x] 회원
    - [x] 회원 가입
        - [x] 화면 마크업 작업
        - [x] 아이디 중복 체크 
        - [x] 회원 가입 시 이용약관 
    - [x] 로그인
        - [x] 화면 마크업 작업
    - [x] 마이 페이지
        - [x] 화면 마크업 작업
        - [x] 회원 정보, 조회 서비스, 채팅 목록, 로그아웃 페이지 이동 버튼 추가
     - [ ] 회원 정보 페이지
        - [ ] 화면 마크업 작업
        - [ ] 회원 정보 수정
        - [ ] 마일리지 잔액 확인
     - [x] 조회 리스트 
        - [x] 화면 마크업 작업
        - [x] 구매 목록 조회 
        - [x] 판매 목록 조회 
        - [x] 관심 목록 조회 
        - [x] 모임 목록 조회
