### ISSUE TITLE
feat/upload

### ISSUE THREAD

**Issue by cheoljundev** [cheoljundev/o2-market#27]
## Description

공통 이미지 업로드 기능 만들기

## Todos

- [x] 공통 이미지 테이블 만들기
- [x] 서비스 클래스 만들기
- [x] 컨트롤러 클래스 만들기
- [x] 테스트하기
