### ISSUE TITLE
feat/half

### ISSUE THREAD

**Issue by cheoljundev** [cheoljundev/o2-market#5]
## Description

반값판매 기능 작업 이슈입니다.

## Todos

- [x] 반값판매 유저단
  - [x] 마이페이지 구매목록
    - [x] 조회
    - [x] 구매확정
  - [x] 상품 리스트
    - [x] 화면 마크업 작업
    - [x] 카테고리 선택을 통한 리스팅
    - [x] 페이징 작업
  - [x] 상품 디테일
    - [x] 화면 마크업 작업
    - [x] 상품 구매 버튼을 통한 구매로 넘어가기
  - [x] 상품 구매
    - [x] 화면 마크업 작업
    - [x] 마일리지 사용
    - [x] 구매하기 처리
- [x] 반값판매 관리자단
  - [x] 주문건 확인
    - [x] 화면 마크업 작업
    - [x] 주문건 조회
    - [x] 주문번호 클릭으로 상세 정보 확인
    - [x] 송장 입력으로 발송
    - [x] 주문건 페이징
  - [x] 이벤트 진행
    - [x] 화면 마크업 작업
    - [x] 추첨 로직 구현
    - [x] 결과를 취소/진행 구현
  - [x] 매입 리스트
    - [x] 화면 마크업 작업
    - [x] 매입건 조회
    - [x] 매입건 페이징 
    - [x] 매입건 상세 정보 확인
    - [x] 매입건 처리를 통한 유저 상품리스트로 업데이트
