### ISSUE TITLE
bug/trade-parameter

### ISSUE THREAD

**Issue by cheoljundev** [cheoljundev/o2-market#53]
## Description

상세 조회 및 등록이 되지 않습니다. 파라미터를 포함해주세요. 수업에서 인텔리제이에서 -parameter 옵션을 넣는 것을 알려주었으나, 실제로는 파라미터를 넣는 것이 최신 스프링부트 정책입니다. IDE설정보다는 스프링부트 정책에 의존하는 것이 좋아보입니다.

bug/trade 브랜치를 메인 브랜치 git pull로 최신화 후, 새로 브랜치를 따서 작업해주세요.

## Todos

- [ ] 거래건 정상 등록
- [ ] 거래건 정상 조회
- [ ] IDE 환경설정에서 옵션 제거하고도 모든 동작 되는지 확인
