### ISSUE TITLE
feat/trade

### ISSUE THREAD

**Issue by ahnjinwon** [cheoljundev/o2-market#7]
## Description

거래 기능 작업 이슈입니다.

## Todos

- [ ] 거래 유저단
  - [x] 거래 게시글 리스트
    - [x] 화면 마크업 작업
    - [x] 카테고리 선택 및 검색을 통한 리스팅
    - [x] 페이징 작업
    - [x] 찜목록을 이용한 리스팅
    - [x] 광고 삽입
    - [x] 내 작성글 보기
  - [x] 거래 게시글 디테일
    - [x] 화면 마크업 작업
    - [x] 클릭 시 조회수 증가
    - [x] 찜 버튼을 통한 찜 추가
    - [x] 이미지 넘기기 구현
    - [x] 삭제 구현
  - [x] 거래 게시글 등록
    - [x] 화면 마크업 작업
    - [x] 멀티 파일 업로드
    - [x] db에 insert 구현
- [x] 거래 관리자단
  - [x] 거래 신청 리스트
    - [x] 화면 마크업 작업
    - [x] 페이징 작업
  - [x] 거래 신청 디테일
    - [x] 화면 마크업 작업
    - [x] 승인 및 거절 구현
  - [x] 광고 리스트
    - [x] 화면 마크업 작업
    - [x] 페이징 작업
  - [x] 광고 디테일
    - [x] 화면 마크업 작업
    - [x] 삭제 구현
  - [x] 광고 등록
    - [x] 화면 마크업 작업
    - [x] 싱글파일 업로드
    - [x] db에 insert 구현

**Comment by ahnjinwon** [comment]
거래 등록 기능 구현

**Comment by ahnjinwon** [comment]
20240625

**Comment by ahnjinwon** [comment]
20240626 거래 게시글 디테일 구현

**Comment by ahnjinwon** [comment]
20240627 찜목록 리스트, 승인 여부 구현, 승인 여부에 따른 리스트 구현,

**Comment by ahnjinwon** [comment]
20240628 upload통일, 카테고리 타임리프동기화, 광고등록 구현, 광고리스트 구현, 랜덤 광고 삽입 구현

**Comment by ahnjinwon** [comment]
20240629 광고 detail구현, 삭제 구현, 페이징 추가, 내 작성글 보기 구현
